name: CI Workflow

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.400'  

      - name: Create AUTH0.env file
        run: |
          mkdir -p src/Auth0
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> src/Auth0/AUTH0.env
          echo "AUTH0_API_IDENTIFIER=${{ secrets.AUTH0_API_IDENTIFIER }}" >> src/Auth0/AUTH0.env
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> src/Auth0/AUTH0.env
          echo "AUTH0_CALLBACK_URL=${{ secrets.AUTH0_CALLBACK_URL }}" >> src/Auth0/AUTH0.env
          echo "AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}" >> src/Auth0/AUTH0.env

      - name: Create BACKEND.env file
        run: |
          mkdir -p src/Backend
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" >> src/Backend/BACKEND.env
          echo "CREATE_USER=${{ secrets.CREATE_USER }}" >> src/Backend/BACKEND.env
          echo "ALL_INGREDIENTS=${{ secrets.ALL_INGREDIENTS }}" >> src/Backend/BACKEND.env

      - name: Build project
        id: build_project  
        run: |
          cd src
          dotnet build

      - name: Notify build failure
        if: failure()  
        run: |
          echo "Build failed! Please check the logs for details."
